adding DevelopmentSetup.md
ElektraInitiative/opensesame pull request #10
Opened 2023-05-28 17:54 UTC by fel115

I created a markdown file to explain the setup of a development environment. This should help developers in the future to set up the environment faster. 

@markus2330 should I create a separate markdown file for troubleshoots?

2023-05-31 12:55 UTC, markus2330 requested changes
Thx for the PR. Great work. Troubleshooting is okay in this file.

2023-05-31 12:55 UTC, markus2330 commented on doc/DevelopmentSetup.md
> +cp file/opensesame.so /usr/share/local/de/LC_MESSAGES/
Is there no way to tell 

```suggestion
cp file/opensesame.mo /usr/share/local/de/LC_MESSAGES/
```

2023-06-01 07:23 UTC, fel115 commented on doc/DevelopmentSetup.md
> +default = https://nextcloud.my-server.com/nextcloud
But if I use the required-statment, which is normally in the spec-file, then I get this error: 

`thread 'main' panicked at 'Did not find the key '/sw/libelektra/opensesame/#0/current/nextcloud/url'!', src/config.rs:121:13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:579:5
   1: core::panicking::panic_fmt
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panicking.rs:64:14
   2: opensesame::config::Config::get
             at ./src/config.rs:121:4
   3: opensesame::nextcloud::Nextcloud::new
             at ./src/nextcloud.rs:20:9
   4: opensesame::main
             at ./src/main.rs:187:26
   5: core::ops::function::FnOnce::call_once
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.`

That's the reason why I changed the spec-file. Is there another way to solve this issue?

2023-06-01 07:38 UTC, markus2330 commented on doc/DevelopmentSetup.md
> +default = https://nextcloud.my-server.com/nextcloud
Please create a separate issue with the exact `kdb set` statement you executed.

2023-06-04 18:03 UTC, atmaxinger commented on doc/DevelopmentSetup.md
> +For the devolpomnet setup you have to do some steps manually, so this page should help you to get you development environment (devl-env) ready to start.
```suggestion
For the development setup you have to do some steps manually, so this page should help you to get you development environment (devl-env) ready to start.
```

2023-06-04 18:19 UTC, atmaxinger commented on doc/DevelopmentSetup.md
> +cp file/opensesame.mo /usr/share/local/de/LC_MESSAGES/
```suggestion
cp files/opensesame.mo /usr/share/locale/de/LC_MESSAGES/
```

2023-06-04 18:19 UTC, atmaxinger commented on doc/DevelopmentSetup.md
> +2. If you get an error with "TranslationNotFound("de")", then you have to copy the opensesame.mo into your local/de directory
```suggestion
2. If you get an error with "TranslationNotFound("de")", then you have to copy the opensesame.mo into your locale/de directory
```

2023-06-05 09:40 UTC, atmaxinger commented on doc/DevelopmentSetup.md
> +3. If you get an IO error in the button.rs file, then you have to [mock the I2CDevice](https://docs.rs/i2cdev/0.5.0/i2cdev/mock/struct.MockI2CDevice.html)
How to do that? Do I need to change code in opensesame?

2023-06-05 09:45 UTC, atmaxinger commented on doc/DevelopmentSetup.md
> +3. If you get an IO error in the button.rs file, then you have to [mock the I2CDevice](https://docs.rs/i2cdev/0.5.0/i2cdev/mock/struct.MockI2CDevice.html)
Well it's currently running on the Olimex board, and I have an Arduino lying around here too, yes.

2023-06-05 09:46 UTC, atmaxinger commented on doc/DevelopmentSetup.md
> +3. If you get an IO error in the button.rs file, then you have to [mock the I2CDevice](https://docs.rs/i2cdev/0.5.0/i2cdev/mock/struct.MockI2CDevice.html)
But sensor-only mode would probably suffice too for my use case

2023-06-05 09:48 UTC, fel115 commented on doc/DevelopmentSetup.md
> +3. If you get an IO error in the button.rs file, then you have to [mock the I2CDevice](https://docs.rs/i2cdev/0.5.0/i2cdev/mock/struct.MockI2CDevice.html)
I haven't done it until now, but the idea is to create a mock for the I2CDevice so you don't have to have a connection to a i2c-device on your development setup. The error looks like that `Ein unbehebbarer Fehler ist bei src/buttons.rs:132: called `Result::unwrap()` on an `Err` value: Io(Os { code: 13, kind: PermissionDenied, message: "Keine Berechtigung" }) passiert`. 

To answer your question, yes you have to add changes to the opensesame code.

2023-06-05 09:50 UTC, atmaxinger commented on doc/DevelopmentSetup.md
> +3. If you get an IO error in the button.rs file, then you have to [mock the I2CDevice](https://docs.rs/i2cdev/0.5.0/i2cdev/mock/struct.MockI2CDevice.html)
Funnily, I have a different error. on a different line

`thread 'main' panicked at 'I2C Communication to Buttons does not work: Nix(ENXIO)', src/buttons.rs:142:14`

2023-06-05 10:07 UTC, markus2330 requested changes
Further fixes.

2023-06-05 10:07 UTC, markus2330 commented on doc/DevelopmentSetup.md
> +For the development setup you have to do some steps manually, so this page should help you to get you development environment (devl-env) ready to start.
What is devl-env? It is only used one more time, so probably not needed to introduce an abbreviation of development environment if this is what you wanted to do.

```suggestion

For the development setup you have to do some steps manually, so this page should help you to get you development environment (devl-env) ready to start.
```

2023-06-05 10:07 UTC, markus2330 commented on doc/DevelopmentSetup.md
> +One importent dependencies is libelektra which can be installed by following [these steps](https://github.com/ElektraInitiative/libelektra/blob/master/doc/INSTALL.md)
```suggestion

One dependency is libelektra which can be installed by following [these steps](https://www.libelektra.org/installation/installation)
```

2023-06-05 10:07 UTC, markus2330 commented on doc/DevelopmentSetup.md
> +## 3. After the build was successfully you have to configure your nextcloud with `kdb set`
First the postinst should be described.


```suggestion

## 3. After the build was successfully you have to configure your nextcloud with `kdb set` 
```

2023-06-05 10:08 UTC, markus2330 commented on doc/DevelopmentSetup.md
> +3. If you get an IO error in the button.rs file, then you have to [mock the I2CDevice](https://docs.rs/i2cdev/0.5.0/i2cdev/mock/struct.MockI2CDevice.html)
> But sensor-only mode would probably suffice too for my use case

So this is best, then you don't need any mocking. Simply install the 
read_analog_input_sketch_aug03a, it should work also without any sensors connected (reading random values if the pins are not connected).

2023-06-05 10:39 UTC, atmaxinger commented on doc/DevelopmentSetup.md
> +cp file/opensesame.mo /usr/share/locale/de/LC_MESSAGES/
```suggestion
cp file/opensesame.mo /usr/share/locale/de/LC_MESSAGES/
cp file/opensesame.mo /usr/share/locale/en/LC_MESSAGES/
```

Also add to the English locale as a workaround, as the default Olimex images is in English.

2023-06-05 11:01 UTC, atmaxinger commented on doc/DevelopmentSetup.md
> +3. If you get an IO error in the button.rs file, then you have to [mock the I2CDevice](https://docs.rs/i2cdev/0.5.0/i2cdev/mock/struct.MockI2CDevice.html)
> read_analog_input_sketch_aug03a

Okay, so if I understand this correctly, the Arduino prints out the measured data from its analog pins onto the USB serial interface. The Arduino is connected to the Olimex board via USB, and opensesame then reads the output of the serial communication.

How do I put opensesame into sensor-only mode?

Alternatively, couldn't I also simulate the I2C buttons using the I2C interface on a Raspberry Pi?

2023-06-05 12:34 UTC, markus2330 commented on doc/DevelopmentSetup.md
> +3. If you get an IO error in the button.rs file, then you have to [mock the I2CDevice](https://docs.rs/i2cdev/0.5.0/i2cdev/mock/struct.MockI2CDevice.html)
> Arduino prints out the measured data from its analog pins onto the USB serial interface. The Arduino is connected to the Olimex board via USB, and opensesame then reads the output of the serial communication.

Exactly.

> How do I put opensesame into sensor-only mode?

If `sensors/#0/loc` is present, only sensors and env¹ are relevant, then buttons etc. settings are ignored. This is currently an limitation: either sensors or the rest is active.

Btw. there is no spec for sensors/ could you please add this?

¹needs (1) my push to master I just did right before bf4a3865de94d842bb2ef81f1f71fcab78683546 and (2) disabling with environment/device = /dev/null

> Alternatively, couldn't I also simulate the I2C buttons using the I2C interface on a Raspberry Pi?

Of course you could, but this is a lot of useless work (the i2c protocols are quite involved). For testing the mocking is the much better option, as you don't need a complicated setup to make it run.

2023-06-05 15:21 UTC, atmaxinger commented on doc/DevelopmentSetup.md
> +## 5. Setup specs and states with Elektra
```suggestion
## 3. Setup specs and states with Elektra
```

2023-07-26 09:04 UTC, fel115 commented on doc/DevelopmentSetup.md
> +kdb set system:/sw/libelektra/opensesame/#0/current/nextcloud/chat "<token>"
change to `kdb set user:/sw/...`

2023-07-27 04:29 UTC, markus2330 requested changes
Something is still wrong with this PR, please rebase correctly or cherry-pick the relevant changes.

2023-07-27 04:29 UTC, markus2330 commented on Cargo.toml
> +version = "0.7.7"
This should already be in master, something went wrong with rebase?

2023-07-27 04:29 UTC, markus2330 commented on doc/DevelopmentSetup.md
> +kdb set system:/sw/libelektra/opensesame/#0/current/nextcloud/chat "<token>"
It is your PR, simply go ahead and push the change :wink:

2023-07-27 04:29 UTC, markus2330 commented on doc/DevelopmentSetup.md
> +In this step you have to run the `postinst` script, which is located in the debian folder. This script setup the specs, states and mount them into elektra.
```suggestion
In this step you have to run `cd debian && ./postinst`. This script mounts the configuration specification and states into elektra. 
```

2023-07-27 04:29 UTC, markus2330 commented on doc/DevelopmentSetup.md
> +Therefore you have to add [nextcloud/url], [nextcloud/chat], [nextcloud/chat/licht], [nextcloud/chat/ping], [nextcloud/user] and [nextcloud/pass]. This is done with the following statements:
```suggestion

As minimum you have to add [nextcloud/url], [nextcloud/chat], [nextcloud/chat/licht], [nextcloud/chat/ping], [nextcloud/user] and [nextcloud/pass]. This is done with the following statements:
```

2023-07-27 04:29 UTC, markus2330 commented on doc/DevelopmentSetup.md
> +# Troubleshoot
Yes, probably better in a separate document and link there.

2023-07-27 04:29 UTC, markus2330 commented on doc/DevelopmentSetup.md
> +1. If you get a panic, with no further information, while running opensesame you have to comment the line 164 out (`panic::set_hook` in main). That's a temporary workarount which is already issued [#
One line per sentence is easier to review:

```suggestion
1. If you get a panic, with no further information, while running opensesame you have to comment the line 164 out (`panic::set_hook` in main).
That's a temporary workarount which is already issued [#6](https://github.com/ElektraInitiative/opensesame/issues/6).
```

2023-07-27 04:29 UTC, markus2330 commented on doc/DevelopmentSetup.md
> +The problem can be solved by executing `/var/lib/dpkg/info/opensesame.postinst`.
Also add #42 (make sure CWD is the debian folder)

2023-07-27 04:29 UTC, markus2330 commented on doc/Emulating-Olimex.md
This was also in an earlier PR? Please make sure that the [files tab](/https://github.com/ElektraInitiative/opensesame/pull/10/files) contains exactly the wanted changes and nothing else.

2023-07-27 09:10 UTC, fel115 commented on doc/DevelopmentSetup.md
> +kdb set system:/sw/libelektra/opensesame/#0/current/nextcloud/chat "<token>"
yeah, I came across this mistake, while I was editing a other PR. I only what to document it for me.

2023-07-27 09:43 UTC, fel115 commented on Cargo.toml
> +version = "0.7.7"
Yes, I think so, but I don't know what. I tried to rebase and in the rebase, I wasn't able to select my new changes during the conflict.

2023-07-30 13:56 UTC, fel115 commented on doc/Emulating-Olimex.md
I don´t know what a file tab is.

2023-07-30 13:58 UTC, fel115 commented on Cargo.toml
> +version = "0.7.7"
I think now everything should work without conflict.

2023-07-30 14:45 UTC, markus2330 commented on doc/Emulating-Olimex.md
Simply press on the link :wink:

2023-07-30 14:50 UTC, merged

2023-07-30 15:22 UTC, fel115 commented on doc/Emulating-Olimex.md
Ahh sorry I didn't mention, I get an 404 error by clicking this link

2023-07-30 15:24 UTC, markus2330 commented on doc/Emulating-Olimex.md
It should've been https://github.com/ElektraInitiative/opensesame/pull/10/files

2023-07-30 15:49 UTC, fel115 commented on doc/Emulating-Olimex.md
OK now I am understanding what you mean :+1: