removed Battery on startup, added Translation; bugfix in Garage output
ElektraInitiative/opensesame pull request #112
Opened 2023-10-16 08:21 UTC by fel115

Issue #104 should be fixed with this PR

2023-10-19 08:52 UTC, markus2330 requested changes
Thank you, many improvements :heart: 
I tried to resolve the conflict but CI does not build anymore.

2023-10-19 08:52 UTC, markus2330 commented on lang/de_AT.po
> +msgid "🔔 Ringing the Audio Bell "
Needs fix in src

```suggestion
msgid "🔔 Ringing the Audio Bell"
```

2023-10-19 08:52 UTC, markus2330 commented on lang/de_AT.po
> +msgstr "🚨 Audio Feueralarm"
```suggestion
msgstr "🚨 Audio Feueralarm!"
```

2023-10-19 08:52 UTC, markus2330 commented on lang/de_AT.po
> +msgstr "🔔 Knopf für Glocke gedrückt. {}"
Should have same arguments, shouldn't it?

```suggestion
msgstr "🔔 Knopf für Glocke gedrückt."
```

2023-10-19 08:52 UTC, markus2330 commented on lang/de_AT.po
> +msgstr "💡 Taster innen gedrückt. {}. {}"
Again different number of arguments?

2023-10-19 08:52 UTC, markus2330 commented on lang/de_AT.po
> +msgstr "🔔 Taster Glocke gedrückt. {}"
again

2023-10-19 08:52 UTC, markus2330 commented on src/signals.rs
> -		self.nextcloud_sender
Why remove this completely? There should be a message when reloading config&state via signals.

2023-10-19 08:57 UTC, markus2330 commented
please also pump version

2023-10-19 16:28 UTC, fel115 commented on src/signals.rs
> -		self.nextcloud_sender
Sorry thought it was the same as at the beginning of the function.

2023-10-20 04:43 UTC, merged

2023-10-20 04:44 UTC, markus2330 commented
Great job, thank you, finally finished :1st_place_medal: