add guide on how to emulate Olimex image
ElektraInitiative/opensesame pull request #15
Opened 2023-06-06 10:00 UTC by atmaxinger

Small basic guide on how to emulate the Olimex board.

2023-06-06 20:22 UTC, fel115 requested changes
All in all this documentation describes the emulation setup perfect, but I had some issue with the binding of `/dev/ttyACM0`, without this bindings I can boot the emulator.

2023-06-06 20:22 UTC, fel115 commented on doc/Emulating-Olimex.md
> +```
I can't bind the `/dev/ttyACM0`, because my system doesn't have such a device. Is it necessary to mount this device?

2023-06-06 20:22 UTC, fel115 commented on doc/Emulating-Olimex.md
> +
Maybe you could include some basic information on, how to mount from an Image. For example, extracting the offset of the partition which should be mounted (``fdisk -l <olimex>.img) and how to  setup the loop-device (losetup -o <part-offset> -f <olimex>.img).

2023-06-06 20:24 UTC, atmaxinger commented on doc/Emulating-Olimex.md
> +```
It's only necessary when you want to bind it. However, opensesame seems to be a bit useless without it.

2023-06-06 20:25 UTC, atmaxinger commented on doc/Emulating-Olimex.md
> +
Well I can't because I don't know. But feel free to add suggestions via the comments on how you set up that.

2023-06-07 11:56 UTC, markus2330 commented on doc/Emulating-Olimex.md
> +```
Everything except of the air-quality sensors works without it (the other devices/sensors use i2c).

2023-06-07 13:33 UTC, fel115 commented on doc/Emulating-Olimex.md
> +
First you need to get the offset of the `olimex.img` for that you need to execute `fdisk -l olimex.img`, now you need to get the starting sector of the image partition, you like to mount. Now you have to multiple the starting sector with the sector-size and this results in the offset. In the next step you have to setup the loop-device with `losetup -o <offset> -f olimex.img`. You can list all you loop-devices with `losetup -l`, to see on which loop-device your image is connected. The last step is to mount the loop-device with `mount /dev/loop0 <mount-dir>`.

2023-06-07 13:58 UTC, merged

2023-06-07 13:58 UTC, markus2330 commented on doc/Emulating-Olimex.md
> +
@fel115 probably easier if you directly write it.

2023-06-07 14:14 UTC, atmaxinger commented on doc/Emulating-Olimex.md
> +
@fel115 systemd-nspawn also has a way of directly working on the image with the [--image](https://www.freedesktop.org/software/systemd/man/systemd-nspawn.html#-i) parameter. Maybe this is easier? You can then use [--overlay](https://www.freedesktop.org/software/systemd/man/systemd-nspawn.html#--overlay=) for persisting the changes.

2023-06-09 09:50 UTC, fel115 commented on doc/Emulating-Olimex.md
> +
With my image it doesn't worked. I get this error message `No suitable root partition found in image 'A20-OLinuXino-bullseye-minimal-20220928-143706.img'.`. It think that's because the image doesn't contain a MBR- or GUID-table.