Update Ansible example for new Elektra module
ElektraInitiative/opensesame pull request #20
Opened 2023-06-16 16:43 UTC by atmaxinger

2023-06-19 05:25 UTC, markus2330 requested changes
Thanks for the update! There are some errors, please fix and test if it actually works.

2023-06-19 05:25 UTC, markus2330 commented on ansible/inventory.yaml
> +      os_nc_user: "haustuer"
Why these `os_` prefixes?

2023-06-19 05:25 UTC, markus2330 commented on ansible/inventory.yaml
> +    os_nc_user: "user"
How is this used?

2023-06-19 05:25 UTC, markus2330 commented on ansible/playbook.yaml
> +    # So we run this task as root user first to disable recording
Problem is clear but goal is not clear: does this playbook intend to not use recording?

2023-06-19 05:25 UTC, markus2330 commented on ansible/playbook.yaml
> +          skip: yes
Shouldn't we make this default then?

2023-06-19 05:25 UTC, markus2330 commented on ansible/playbook.yaml
> +                timeout: 24
Somehow indentation got lost here. Enable of ping imho should be some global setting, people might not like it to get regular pings (if they already have other means of monitoring).

2023-06-19 05:25 UTC, markus2330 commented on ansible/playbook.yaml
> +                enable: "{{ os_dell_enable | default('0', true) }}"
```suggestion
                enable: "{{ os_bell_enable | default('0', true) }}"
```

2023-06-19 05:25 UTC, markus2330 commented on ansible/playbook.yaml
>  - name: Configure opensesame specific to schreibtisch
```suggestion
- name: Add sensor configuration
```

2023-06-19 05:25 UTC, markus2330 commented on ansible/inventory.yaml
>      schreibtisch:
Maybe call it "sensors" or something like this (I renamed it now messstation in my setup).

2023-06-19 05:25 UTC, markus2330 commented on ansible/playbook.yaml
>     - name: set keys for opensesame
I assume it adds? (leaves the other keys unchanged)

```suggestion
   - name: add keys for opensesame
```

2023-06-19 06:28 UTC, atmaxinger commented on ansible/inventory.yaml
> +      os_nc_user: "haustuer"
It stands for opensesame. As we intend for the users to use this playbook as a template to configure their own environments, I figured that it might be a good idea to avoid possible name clashes from the beginning. Also, IMHO, it makes it much clearer visibly to see that those variables belong together in a certain way.

2023-06-19 06:33 UTC, atmaxinger commented on ansible/playbook.yaml
> +          skip: yes
I'm not sure. Here it is a unique scenario, as for some reason the opensesame configuration is configured in a user's namespace. TBH, I don't see why anyone would do this on managed nodes. I'd just use the `system` namespace and then we can always configure it as root.

2023-06-19 08:56 UTC, markus2330 commented on ansible/inventory.yaml
> +      os_nc_user: "haustuer"
ahh ok, I didn't think of os = opensesame :wink:

2023-06-19 08:59 UTC, markus2330 commented on ansible/playbook.yaml
> +          skip: yes
Of course it would be best if recording of user: by a user would simply succeed. Where is this behavior documented for Elektra's tooling?

2023-06-19 16:20 UTC, atmaxinger commented on ansible/playbook.yaml
> +          skip: yes
Recording of user: is not the problem. Deactivating recording is. Seems like it's currently not documented, will create a PR for the manpages.

2023-07-03 09:55 UTC, atmaxinger commented on ansible/inventory.yaml
> +    os_nc_user: "user"
These are the default values if not otherwise specified

2023-07-17 12:09 UTC, fel115 approved these changes

2023-08-18 13:08 UTC, markus2330 approved these changes
thx

2023-08-18 13:08 UTC, merged