Adding book.toml for mdbook
ElektraInitiative/opensesame pull request #31
Opened 2023-07-17 12:30 UTC by fel115

I added the book.toml file for mdbook. Should I also push the generated files from mdbook ?

2023-07-17 13:36 UTC, markus2330 requested changes
Doesn't work for me, I get:

```
2023-07-17 15:35:16 [ERROR] (mdbook::utils): Error: Couldn't open SUMMARY.md in "/home/markus/Projekte/Opensesame/opensesame/doc" directory
2023-07-17 15:35:16 [ERROR] (mdbook::utils):    Caused By: No such file or directory (os error 2)
```

SUMMARY.md needs to list all the files we want to include.

The generated book (html) should not be checked in, eventually the CI will build and publish it.

2023-07-17 17:09 UTC, fel115 commented
It should work now. I forgot to add the SUMMARY.md file in the PR.

2023-07-17 17:34 UTC, markus2330 requested changes

2023-07-17 17:34 UTC, markus2330 commented on doc/SUMMARY.md
> +# Summary
Here should be a list of files in the order they should be shown. Please go over the documents and check if the:

- title is okay
- content is formatted properly

e.g. doc/Install.md should be the first document, with `Install` (or similar) as title and nice code formatting throughout.

2023-07-18 08:41 UTC, fel115 commented on doc/SUMMARY.md
> +# Summary
Is this order okay?

2023-07-19 13:52 UTC, markus2330 approved these changes
Thank you, much better!

2023-07-19 13:52 UTC, markus2330 commented on doc/SUMMARY.md
> +- [Translations](Translastions.md)
```suggestion
- [Translations](Translations.md)
```

2023-07-19 13:53 UTC, merged