changes in rust file for testing of connection
ElektraInitiative/opensesame pull request #43
Opened 2023-07-24 13:28 UTC by fel115

I can't compile the Rust-Code because there are two different versions of `clang` needed. 

```
error: failed to select a version for `clang-sys`.
    ... required by package `bindgen v0.55.1`
    ... which satisfies dependency `bindgen = "^0.55.1"` of package `libmodbus-sys v1.0.0 (https://github.com/ElektraInitiative/libmodbus-rs.git?branch=impl-modbus_rtu_set_custom_rts#0d90b7e6)`
    ... which satisfies git dependency `libmodbus-sys` of package `libmodbus v1.0.0 (https://github.com/ElektraInitiative/libmodbus-rs.git?branch=impl-modbus_rtu_set_custom_rts#0d90b7e6)`
    ... which satisfies git dependency `libmodbus` of package `opensesame v0.7.7 (/home/smod/Bachelorarbeit/GitHub/opensesame)`
versions that meet the requirements `^1` are: 1.6.1, 1.6.0, 1.4.0, 1.3.3, 1.3.2, 1.3.1, 1.3.0, 1.2.2, 1.2.1, 1.2.0, 1.1.1, 1.1.0, 1.0.3, 1.0.2, 1.0.1, 1.0.0

the package `clang-sys` links to the native library `clang`, but it conflicts with a previous package which links to `clang` as well:
package `clang-sys v0.28.1`
    ... which satisfies dependency `clang-sys = "^0.28.0"` (locked to 0.28.1) of package `bindgen v0.50.1`
    ... which satisfies dependency `bindgen = "^0.50.0"` (locked to 0.50.1) of package `elektra-sys v0.9.10`
    ... which satisfies dependency `elektra-sys = "^0.9.1"` (locked to 0.9.10) of package `elektra v0.9.10`
    ... which satisfies dependency `elektra = "^0.9.10"` (locked to 0.9.10) of package `opensesame v0.7.7 (/home/smod/Bachelorarbeit/GitHub/opensesame)`
Only one package in the dependency graph may specify the same links value. This helps ensure that only one copy of a native library is linked in the final binary. Try to adjust your dependencies so that only one package uses the links ='clang-sys' value. For more information, see https://doc.rust-lang.org/cargo/reference/resolver.html#links.

failed to select a version for `clang-sys` which could resolve this conflict
```

@markus2330 whats the best way to remove this conflict?

2023-07-24 17:11 UTC, markus2330 commented
Why are two different versions of clang needed? I think we should fix that and use the same version. Let us use the same version as in PermaplanT, i.e. rustc 1.67.1 (d5a82bbd2 2023-02-07)

If there are problems in compiling Elektra or Opensesame with that version, we should fix these problems.

2023-07-25 06:19 UTC, fel115 commented
Changing to rustc 1.67.1 makes no changes to this conflict. I think the conflict is, because libmodbus-sys uses `bindgen=0.55.1` and elektra uses `bingen=0.50.0`. Maybe it is possible to use a higher version of elektra?

2023-07-25 06:42 UTC, markus2330 commented
@atmaxinger can you try to pump that version in Elektra's binding? The rust release is done manually, anyway.

2023-07-27 10:43 UTC, fel115 commented
For now it is hard to test the new implementation of `clima_sensor_us.rs` because I can`t compile the project.

2023-07-27 12:50 UTC, markus2330 requested changes
Carry on :rocket:

2023-07-27 12:50 UTC, markus2330 commented on files/opensesame.spec
> +
I don't think so much configuration is needed. Let us keep it to a minimum. Only when sensors with such settings are actually sold we should add these settings. Instead use const vars.

2023-07-27 12:50 UTC, markus2330 commented on src/weather_station/clima_sensor_us.rs
> +    pub fn handle_temperature(&mut self) -> Result<bool,Error> {
Is more consistent and also more correct (as it handles more than temperature).

```suggestion
    pub fn handle(&mut self) -> Result<bool,Error> {
```

2023-07-27 12:50 UTC, markus2330 commented on src/weather_station/clima_sensor_us.rs
> +
Why these empty lines?

2023-07-27 12:50 UTC, markus2330 commented on src/weather_station/clima_sensor_us.rs
> +    /// This function should be called periodically to check the temperature and wind speed.
```suggestion
    /// This function should be called periodically to check the sensors' values.
```

2023-07-27 12:50 UTC, markus2330 commented on src/weather_station/clima_sensor_us.rs
> +    /// if temp < 20° the warning should be removed
```suggestion
    /// if temp < 20° either warning is removed
    ///
    /// if temp > 23° a message is sent that open windows should be closed
```

2023-07-27 12:50 UTC, markus2330 commented on src/weather_station/clima_sensor_us.rs
> +    /// The return value is bool on success, true if alarm is active and false is alarm is not active
I think you will eventually need an enum

2023-07-30 16:48 UTC, fel115 commented
How should we implement the registers of the weather station? I thought about a csv-file which would look like there following example:

```csv
reg-addr;param name; unit; multiplier; datatype
30003; Mittelwert Windgeschwindigkeit; m/s; 10; u32
30011;Maximalwert Windgeschwindigkeit (Böe); m/s; 10; u32
...
30401; Lufttemperatur; °C; 10; s32
```

I think this would be necessary, because if we only dump the registers with no further knowledge about the value we can't use it.

2023-07-30 16:55 UTC, markus2330 commented
This issue is not really the right place to discuss it but as the answer is simple I write it here: please hard-code everything in the source code. (const variables etc. as the other modules have). For now it is enough to support this one sensor and metric units, so no configuration is necessary.

2023-07-31 09:37 UTC, fel115 commented
Now compiling should work and I also added the implementation of the handle() function into the main.rs. But for some reason, I cant see these changes in the `Files Changed`-Tab. Have I done something wrong with the rebase or push?

2023-07-31 16:59 UTC, markus2330 approved these changes
LGTM!

2023-07-31 16:59 UTC, markus2330 commented on Cargo.toml
> +libmodbus = {git = "https://github.com/ElektraInitiative/libmodbus-rs.git", branch="impl-modbus_rtu_set_custom_rts"}
use master instead

2023-07-31 16:59 UTC, markus2330 commented on Cargo.toml
> +name = "weatherstation_conn"
probably this simply could be weatherstation_dump: reading all registers instead of just any.

2023-07-31 16:59 UTC, markus2330 commented on src/weather_station/clima_sensor_us.rs
> +//Special reg-addresses
They are not special, are they?

```suggestion
// Addresses of registers.
```

2023-07-31 16:59 UTC, markus2330 commented
> Error: file `/home/jenkins/workspace/opensesame_PR-43/weather_station/connection_modbus.rs` does not exist

CI fails.

2023-08-01 06:33 UTC, fel115 commented
> Weird, what do you see there? I see 4 changed files. see also the review.

On this [site](https://github.com/ElektraInitiative/opensesame/compare/e9c8a19c02531d3686992e23648236ad36d5800e..f72e172839477027820a206e2fda68f497bb83b8) you can see my last changes after rebase. I changed the location of `clima_sensor_us.rs` and did some changes to the `main.rs`

2023-08-01 06:38 UTC, fel115 commented on Cargo.toml
> +name = "weatherstation_conn"
So, weatherstation_dump shouldn't be integrated into the clima_sensor_us.rs module?

2023-08-01 06:46 UTC, fel115 commented
> > Error: file `/home/jenkins/workspace/opensesame_PR-43/weather_station/connection_modbus.rs` does not exist
> 
> CI fails.

This could be, because there isn't the full path to the file. The full path would be `src/weather_station/connection_modbus.rs`. But the question is if we really need this file now. This file was only for testing the weather station.

2023-08-01 07:14 UTC, fel115 commented on Cargo.toml
> +libmodbus = {git = "https://github.com/ElektraInitiative/libmodbus-rs.git", branch="impl-modbus_rtu_set_custom_rts"}
If we use master, we also need an updated version of Elektra to solve the conflict with `bingen`.

2023-08-03 04:43 UTC, markus2330 commented on Cargo.toml
> +libmodbus = {git = "https://github.com/ElektraInitiative/libmodbus-rs.git", branch="impl-modbus_rtu_set_custom_rts"}
Yes, let us update Elektra 0.11.0.

2023-08-03 08:10 UTC, markus2330 commented
CI definitely should not fail, so we cannot merge this. Can you give me an order in which you would like the PRs to be merged. And mark PRs to be merged with "please merge".

2023-08-09 17:50 UTC, markus2330 commented
@fel115 I think this can be closed?

2023-08-14 07:18 UTC, fel115 commented
Yes

2023-08-14 07:18 UTC, closed without merging