Publish to opensensemap
ElektraInitiative/opensesame pull request #49
Opened 2023-07-31 14:48 UTC by fel115

@markus2330: Which data should be published to `opensesemap.org`? And do I need to create an account for this task?

2023-07-31 17:25 UTC, markus2330 commented
> @markus2330: Which data should be published to opensesemap.org?

Everything of the weather station.

> And do I need to create an account for this task?

I created one for you but I did not create the box yet, please do that.

2023-08-01 08:17 UTC, fel115 commented
@markus2330 I tried to reproduce the function `send_message_once` from the `nextcloud.rs` file. But if I try to implement it in my code, I always get some compiling errors, because I don't use async functions. 
```
expected opaque type, found enum `Result`
```

Have you any idea what's the problem here? Have you had the same issue?

2023-08-01 08:29 UTC, fel115 commented
> @markus2330 I tried to reproduce the function `send_message_once` from the `nextcloud.rs` file. But if I try to implement it in my code, I always get some compiling errors, because I don't use async functions.
> 
> ```
> expected opaque type, found enum `Result`
> ```
> 
> Have you any idea what's the problem here? Have you had the same issue?

NVM. I now used the same versions of reqwest, tokio and futures for testing. And now it's compiling and working. :relaxed:

2023-08-03 04:42 UTC, markus2330 commented
> So it should be like a register dump? But with the extension to upload the data? How should I store the registers, in a csv file?

I am not sure if I understand. With the weather station you will always read the registers. So the difference is always only what is afterwards done with the data. I hope I could clarified the different use cases in #50. Ideally we should write down the use cases explicitly as done in PermaplanT, see https://github.com/ElektraInitiative/PermaplanT/tree/master/doc/usecases

2023-08-03 07:22 UTC, fel115 commented
I think usecases would be a good idea . 👍

Now I'm saving the registers, the opensensemap-id, factor and datatype of the sensors in a constant, should this be moved to a CSV file or something else? As I know Elektra is only a key:value database, so we can't store this information there. Or should we stay with the constance's?

The box-id an access token could be stored in Elektra or is this a task for later?

2023-08-04 14:36 UTC, fel115 commented
It should be mergeable now. But I couldn't test it on `messstation`, because of #51. CI should also run without errors.

2023-08-04 17:52 UTC, markus2330 requested changes
Great job, good to have some data already online. Looking forward to see it constantly running soon.

2023-08-04 17:52 UTC, markus2330 commented on doc/Opensensemap.md
> +### 2.4 Set Hardware, with `Manual configuration`
What hardware to add for clima_sensor_us?

2023-08-04 17:52 UTC, markus2330 commented on doc/Opensensemap.md
> +### 3.2 Set a name/phenomenon, unit and type (use of const reg-name in clima_sensor_us.rs)
at least what is in the brackets could be normal text and not in a title?

2023-08-04 17:52 UTC, markus2330 commented on files/opensesame.spec
> +[opensensemap/box_id]
Probably put below weatherstation or do you think there is something else to publish? (I don't think so.)

```suggestion
[weatherstation/opensensemap/id]
```

2023-08-04 17:52 UTC, markus2330 commented on files/opensesame.spec
> +description = Which opensensemap Box should be connected to the weather station
```suggestion
description = Which opensensemap Box should be connected to the weather station, see doc/Opensensemap.md
```

2023-08-04 17:52 UTC, markus2330 commented on files/opensesame.spec
> +description = Access-Token for opensensemap Box
```suggestion
description = Access-Token for opensensemap box
```

2023-08-04 17:52 UTC, markus2330 commented on files/opensesame.spec
> +[opensensemap/access_token]
Avoid separators other than /:

```suggestion
[weatherstation/opensensemap/token]
```

2023-08-04 17:52 UTC, markus2330 commented on src/main.rs
> +					nc.send_message(gettext!("Temperature above {}°C, close the window", 23));
Please also translate texts.

2023-08-04 17:52 UTC, markus2330 commented on src/weather_station/connection_modbus.rs
> +/*This program tests if the connection with the weather station is possible and for that reason the register 40015 is read.*/
This program eventually should read all registers and dump it to stdout (redirect to file can be done by the user).

2023-08-04 17:52 UTC, markus2330 commented on src/clima_sensor_us.rs
> +/// [opensensemap/box_id] and [opensensemap/access_token]
Isn't weatherstation/enable needed, too?

2023-08-04 17:52 UTC, markus2330 commented on src/clima_sensor_us.rs
> +const UPDATE_FREQU: u32 = 30000; // 30000ms*10ms = 5min
Is it written like this in the data sheet? If it is, you can keep it as-is, otherwise I would prefer fully-written names:

```suggestion
const UPDATE_FREQUENCY: u32 = 30000; // 30000ms*10ms = 5min
```

2023-08-04 17:52 UTC, markus2330 commented on src/clima_sensor_us.rs
> +				.expect("Error accured while creating new RTU Object"),
Typo is several times:

```suggestion
				.expect("Error occurred while creating new RTU Object"),
```

2023-08-04 17:52 UTC, markus2330 commented on src/clima_sensor_us.rs
> +	#[ignore]
disabled? Please also add a test with JSON data.

2023-08-04 17:52 UTC, markus2330 commented on src/clima_sensor_us.rs
> +				let mut json_payload: String = "[".to_string();
creation of JSON data could be in its own function (publish_to_opensensemap is too long)

2023-08-04 17:52 UTC, markus2330 commented on src/clima_sensor_us.rs
> +				//Send Jason to https://api.opensensemap.org
```suggestion
				//Send JSON to https://api.opensensemap.org
```

2023-08-04 17:52 UTC, markus2330 commented on src/clima_sensor_us.rs
> +							eprintln!("publishing to opensensemap failed with {}", error);
Modules shouldn't print, instead the error should be propagated to main and there it should be sent to nextcloud (translated string).

2023-08-04 17:52 UTC, markus2330 commented on doc/Opensensemap.md
> +
Text missing?

2023-08-04 19:15 UTC, fel115 commented on doc/Opensensemap.md
> +
I meant  the creation of an account, which I think, is self explaining.

2023-08-05 03:43 UTC, markus2330 commented on doc/Opensensemap.md
> +
Then write something like:

```suggestion

After you've setup your account and logged in on [opensensemap.org](https://www.opensensemap.org/), you need to do following steps:

```

2023-08-07 07:01 UTC, fel115 commented on doc/Opensensemap.md
> +### 2.4 Set Hardware, with `Manual configuration`
It is possible to use hardware that is known from opensensemap, but to configure other sensors you need to set all sensors manually.  So config option is called Hardware.

2023-08-07 07:12 UTC, fel115 commented on src/weather_station/connection_modbus.rs
> +/*This program tests if the connection with the weather station is possible and for that reason the register 40015 is read.*/
Yes, I think that's a good idea.

2023-08-07 07:15 UTC, fel115 commented on src/clima_sensor_us.rs
> +/// [opensensemap/box_id] and [opensensemap/access_token]
I implemented the enable in the `main.rs`, should it be implemented in the `clima_sensor_us.rs`?

2023-08-07 07:21 UTC, fel115 commented on src/clima_sensor_us.rs
> +const UPDATE_FREQU: u32 = 30000; // 30000ms*10ms = 5min
No, I used `UPDATE_FREQUENCY` to read all registered every 5 min. Instead of calling them all 10 ms. So it is nothing form the data sheet.

2023-08-07 08:04 UTC, markus2330 commented on doc/Opensensemap.md
> +### 2.4 Set Hardware, with `Manual configuration`
There are endless possibilities but we only implement and document the one hardware with all its features (until someone shows up and needs something else). Please describe here exactly what you changed in the Web-Interface, so that all sensor data gets displayed.

2023-08-07 08:05 UTC, markus2330 commented on src/clima_sensor_us.rs
> +/// [opensensemap/box_id] and [opensensemap/access_token]
I was only referring to the incomplete documentation here.

2023-08-07 08:06 UTC, markus2330 commented on src/clima_sensor_us.rs
> +const UPDATE_FREQU: u32 = 30000; // 30000ms*10ms = 5min
And we probably should use 1 minute, as the web-interface from opensensemaps suggests that updates happen every minute.

2023-08-07 08:10 UTC, markus2330 commented on src/clima_sensor_us.rs
> +const UPDATE_FREQU: u32 = 30000; // 30000ms*10ms = 5min
One important change needed: the weatherstation needs to be integrated in the sensors loop, so that messstation can get both weatherstation and air quality data. The frequency also needs to be adapted to make this work. (The sensors loop gets called much less frequently).

(Later we can remove all loops and use tokio instead but for now let us keep these two loops.)

2023-08-07 09:51 UTC, fel115 commented on src/clima_sensor_us.rs
> +const UPDATE_FREQU: u32 = 30000; // 30000ms*10ms = 5min
Is the sensor loop, where `environment.handle()` is called?

2023-08-07 10:11 UTC, fel115 commented on src/clima_sensor_us.rs
> +	#[ignore]
I disabled it because for testing I need to mock the modbus connection and for testing the JSON I also need to mock the modbus connection.

2023-08-07 10:14 UTC, markus2330 commented on src/clima_sensor_us.rs
> +const UPDATE_FREQU: u32 = 30000; // 30000ms*10ms = 5min
yes, e.g. line 236, and writeln in 240 could be modified to log some of the weather data also on the HD.

2023-08-07 10:15 UTC, markus2330 commented on src/clima_sensor_us.rs
> +	#[ignore]
You might be able to have a function that only returns JSON without publishing it.

2023-08-07 10:26 UTC, fel115 commented on src/clima_sensor_us.rs
> +const UPDATE_FREQU: u32 = 30000; // 30000ms*10ms = 5min
But for me, it looks like line 236 isn't called in an endless loop. I thought this is the initialization of the env sensor.

2023-08-07 10:31 UTC, fel115 commented on src/clima_sensor_us.rs
> +	#[ignore]
Yes, but the JSON function also reads the register from the weather station. Or should I read the register in an extra function and save the register values in an array?

2023-08-07 10:40 UTC, markus2330 commented on src/clima_sensor_us.rs
> +	#[ignore]
If the refactoring doesn't make sense by itself (shorter functions), it is also okay to not have a JSON generation test.

2023-08-07 10:45 UTC, fel115 commented on src/clima_sensor_us.rs
> +const UPDATE_FREQU: u32 = 30000; // 30000ms*10ms = 5min
Okay, so, in that case, the while loop (main.rs line 299) is never called and the other functions are implied disabled.

2023-08-07 10:46 UTC, markus2330 commented on src/clima_sensor_us.rs
> +const UPDATE_FREQU: u32 = 30000; // 30000ms*10ms = 5min
Yes, in the sensors mode everything else is currently disabled.

2023-08-09 17:50 UTC, markus2330 commented
@fel115 please resolve conflicts/rebase so that the CI can check cargo clippy

2023-08-14 06:41 UTC, fel115 commented on src/weather_station/connection_modbus.rs
> +/*This program tests if the connection with the weather station is possible and for that reason the register 40015 is read.*/
Done in PR #52

2023-08-14 06:46 UTC, fel115 commented on src/clima_sensor_us.rs
> +	#[ignore]
created two separate methods, one for sending the data to opensensemap and one for getting data from the weather station and making a JSON format

2023-08-14 16:19 UTC, markus2330 requested changes
It is getting better :rocket: I found many little things and a logic error.

2023-08-14 16:19 UTC, markus2330 commented on src/clima_sensor_us.rs
> +/// Before using this module you need to configure elektra with the following elements
```suggestion
/// Before using this module you need to configure Elektra with the following elements
```

2023-08-14 16:19 UTC, markus2330 commented on src/clima_sensor_us.rs
> +			clima_sens.set_warning_active(33.0, 3.5) == TempWarningStateChange::ChangeToCloseWindow
This shouldn't be triggered again. Warnings only can go one level up, but are only completely cancelled (they don't go down one by one).

2023-08-14 16:19 UTC, markus2330 commented on lang/opensesame.pot
> +msgid "Temperature above {}°C an no Wind"
```suggestion
msgid "Temperature above {}°C and no Wind"
```

2023-08-14 16:19 UTC, markus2330 commented on lang/de_AT.po
> +msgid "Temperature above {}°C an no Wind"
(should be regenerated, fix in source code)

```suggestion
msgid "Temperature above {} °C and no Wind"
```

2023-08-14 16:19 UTC, markus2330 commented on lang/de_AT.po
> +msgid "Temperature above {}°C"
```suggestion
msgid "Temperature above {} °C"
```

2023-08-14 16:19 UTC, markus2330 commented on lang/de_AT.po
> +msgstr "Es hat über {}°C"
```suggestion
msgstr "Es hat über {} °C"
```

2023-08-14 16:19 UTC, markus2330 commented on lang/de_AT.po
> +msgid "Temperature again under {}°C, remove warning"
```suggestion
msgid "Temperature again under {} °C, warning was removed"
```

2023-08-14 16:19 UTC, markus2330 commented on lang/de_AT.po
> +msgstr "Es hat unter {}°C, die Warnung wird entfernt"
```suggestion
msgstr "Es hat unter {} °C, die Warnung wird entfernt"
```

2023-08-14 18:14 UTC, fel115 commented on doc/Opensensemap.md
> +Find the senseBox-ID in the `Dashboard` section.
No, I used mine, but it is possible to transfer the box to another account. I can generate a token that you insert in your account and then the box belongs to your account.

2023-08-14 18:40 UTC, fel115 commented on doc/Opensensemap.md
> +Enable sensor mode by creating a sensor profile with the following settings:
@markus2330 should I add here the workaround with `kdb editor ...`?

2023-08-14 18:53 UTC, fel115 commented on src/main.rs
> +						.unwrap();
The Env also outputs its values in a new line. Should we really use `write!`?

2023-08-14 19:17 UTC, fel115 commented on src/main.rs
> +						.unwrap();
In this line I only output, if an error occurs. The sensor data need to be printed in the `create_json` of the clima_sensor_us module.

2023-08-15 04:14 UTC, markus2330 commented on src/main.rs
> +						nc.send_message(gettext!("Temperature above {}°C, close the window", 23));
Simply a search in the Internet for emojis or unicode (together with the term of what you want).

2023-08-15 04:15 UTC, markus2330 commented on doc/Opensensemap.md
> +Find the senseBox-ID in the `Dashboard` section.
Yes, please send me the token via email.

2023-08-15 04:17 UTC, markus2330 commented on doc/Opensensemap.md
> +Enable sensor mode by creating a sensor profile with the following settings:
If the code here does not work, write something that does work or simply use pseudo-code and leave it up to the user (I'll use Ansible anyway).

2023-08-15 04:20 UTC, markus2330 commented on src/main.rs
> +						.unwrap();
If it is only error, then don't write it all into this file. The file should only contain valid data.

2023-08-15 04:21 UTC, markus2330 commented on src/main.rs
> +						.unwrap();
If it is only error, then don't write it all into this file. The file should only contain valid measurement data.

In the long term, I want to get rid of this file anyway.

2023-08-15 17:16 UTC, markus2330 requested changes
Logic error does not seem to be fixed yet? Please send token and please always rerequest review once you are finished. The cycles should become faster to get enough done in August.

2023-08-15 17:16 UTC, markus2330 commented on doc/Opensensemap.md
> +In this illustrative scenario, the variable `REG_AIR_TEMP` represents the air temperature. Our initial action involves transferring the parameter designation `Air temperature` to the `Phenomenon` inp
```suggestion
In this illustrative scenario, the variable `REG_AIR_TEMP` represents the air temperature.
Our initial action involves transferring the parameter designation `Air temperature` to the `Phenomenon` input section.
Subsequently, we proceed to incorporate `°C` from the provided table into the `Unit` input section.
Finally, the variable name `REG_AIR_TEMP` is copied into the `Type` input field.
```

2023-08-15 17:16 UTC, markus2330 commented on src/main.rs
> +							23
Use constants for these numbers.

2023-08-16 06:57 UTC, markus2330 commented
Please also pump version in Cargo.toml/lock here, so that we know if correct version is used. On messstation now an old version might be running again?)

2023-08-16 09:38 UTC, fel115 commented
> Logic error does not seem to be fixed yet? Please send token and please always rerequest review once you are finished. The cycles should become faster to get enough done in August.

The logic error should be removed already. I added a new test line to check it, but it seems to work. I implemented it so that the states can move up, but only down if the `RemoveWarning` temperature is reached.

Which version do you mean? The Cargo.toml/lock in this PR are up to date with my local version.

2023-08-16 18:22 UTC, horenso requested changes
Looks good, I just suggested some minor things to fix or add TODOs.

2023-08-16 18:22 UTC, horenso commented on src/clima_sensor_us.rs
> +	fn init(&mut self) {
init should return a `Result<(), SomeErrorType>` so that we don't have to `expect()` everything here. If you want to panic if init fails we can do that in the caller.

2023-08-16 18:22 UTC, horenso commented on src/clima_sensor_us.rs
> +			s.init();
So panic here if `init()` returns error, add a TODO and make init() return a `Result` would be the easiest for now,
of of course make new() return a `Result` as well.

2023-08-16 18:22 UTC, horenso commented on src/clima_sensor_us.rs
> +			&& !matches!(self.warning_active, TempWarning::WarningTempNoWind)
```suggestion
			&& !matches!(self.warning_active, TempWarning::WarningTemp | TempWarning::WarningTempNoWind)
```

you can match on multiple variants here

2023-08-16 18:22 UTC, horenso commented on src/clima_sensor_us.rs
> +			&& !matches!(self.warning_active, TempWarning::RemoveWarning)
```suggestion
		} else if !matches!(self.warning_active, TempWarning::None | TempWarning::RemoveWarning)
```

2023-08-17 05:17 UTC, fel115 commented on src/clima_sensor_us.rs
> +			&& !matches!(self.warning_active, TempWarning::WarningTempNoWind)
Thanks for that information, looks much cleaner. :smiley:

2023-08-17 05:42 UTC, markus2330 requested changes
Version not pumped as requested, didn't look further. Please also fix all other problems.

2023-08-17 05:43 UTC, markus2330 commented
CI also fails, please always check this before requesting reviews.

2023-08-17 05:53 UTC, fel115 commented on src/clima_sensor_us.rs
> +			s.init();
What do you mean with 'add a TODO'?

2023-08-17 06:02 UTC, fel115 commented on src/clima_sensor_us.rs
> +									"{}\"sensor\":\"{}\",\"value\":\"{}\"{},",
Thanks for that info, I'll create a TODO

2023-08-17 06:19 UTC, fel115 commented
> Version not pumped as requested, didn't look further. Please also fix all other problems.

What is missing?

> CI also fails, please always check this before requesting reviews.

Yes, I requested a review yesterday and did changes today. But now it should work.

2023-08-17 16:50 UTC, horenso commented on src/clima_sensor_us.rs
> +			s.init();
Sorry if that was unclear. I would suggest we make both `new` and `init` return a `Result`. Then in `main` you properly want to panic for now if `new()` returns an error. So in `main` we just do this:

```
let mut weather_station = ClimaSensorUS::new(&mut config).expect("Could not create weather station!");
```

Then we only use `expect` in one place ^^

2023-08-18 11:53 UTC, markus2330 commented
> What is missing?

Pumping (i.e. increasing) the version number of opensesame (in [Cargo.toml](https://github.com/ElektraInitiative/opensesame/pull/49/files#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542) and Cargo.lock) Please always ask if something is unclear.

> Yes, I requested a review yesterday and did changes today.

Let us better do it the other way round next time.

For me the deb from the build server on messstation does not work (I also tried restarting):

```
Failed to init libmodbus connection: Rtu { msg: "rtu_set_serial_mode", source: Os { code: 95, kind: Uncategorized, message: "Operation not supported" } }
```

Maybe something in `debian/service` is causing the problem (NoNewPrivileges=true or ProtectSystem=full)? Any ideas?

Btw. there are spelling errors in the PR. Let us use some spell checker to make this easier for both of us: #64

2023-08-18 13:25 UTC, fel115 commented
> Pumping (i.e. increasing) the version number of opensesame (in [Cargo.toml](https://github.com/ElektraInitiative/opensesame/pull/49/files#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542) and Cargo.lock) Please always ask if something is unclear.

Now I understand it :sweat_smile: 

> For me the deb from the build server on messstation does not work (I also tried restarting):
> 
> ```
> Failed to init libmodbus connection: Rtu { msg: "rtu_set_serial_mode", source: Os { code: 95, kind: Uncategorized, message: "Operation not supported" } }
> ```
> 
> Maybe something in `debian/service` is causing the problem (NoNewPrivileges=true or ProtectSystem=full)? Any ideas?


I encountered this error only when I switched from using `RtuRS232` to `RtuRS485` mode. It's possible that an additional privilege is required, which might not be configured during the Opensesame installation. The system functions perfectly without Opensesame installed. The specific permission we require is for `rtu_set_custom_rts(RequestToSendMode::RtuRtsUp)` in order to manipulate the GPIO pins.

2023-08-18 14:00 UTC, markus2330 commented
There is a conflict, please fix.

The requirements changed a bit, see #65 (22 instead of 23 etc.).

>   I encountered this error only when I switched from using RtuRS232 to RtuRS485 mode. It's possible that an additional privilege is required, which might not be configured during the Opensesame installation. The system functions perfectly without Opensesame installed. The specific permission we require is for rtu_set_custom_rts(RequestToSendMode::RtuRtsUp) in order to manipulate the GPIO pins.

Could you please find out on messstation which permission it is?

I now claimed the device, hopefully it continues working. Sensebox ID is 64cb602193c69500072a580f

Will review later, I am not sure if I can today. But without the permission error fixed, the weather station is not finished anyway. Would love to see it running as normal installed service :rocket:

2023-08-18 20:02 UTC, fel115 commented
> There is a conflict, please fix.

Is done.

> The requirements changed a bit, see #65 (22 instead of 23 etc.).

I will take a look at it, after I fixed the issue with the `.deb` installation.

> I now claimed the device, hopefully it continues working. Sensebox ID is 64cb602193c69500072a580f

I tested it by starting opensesame in debug mode and it is still working.

> Could you please find out on messstation which permission it is?
> Will review later, I am not sure if I can today. But without the permission error fixed, the weather station is not finished anyway. Would love to see it running as normal installed service 🚀

I tried to change the permission but it didn't change anything. It's really strange, I have no idea why it isn't working. I compiled a release of the opensesame version and with that, it works perfectly, but by installing the service nothing is working. For now, I am stuck, I have no idea what I could do. I changed the service-file to run as root and it didn't work. I tried to execute it manually and it didn't work. Could it be something while creating the `.deb` file ?

2023-08-21 05:16 UTC, markus2330 requested changes
> I will take a look at it, after I fixed the issue with the .deb installation.

It is not a good approach to make unrelated bug fixes dependent on each other. On the contrary: you get better throughput of work when you fix everything that you can fix and give that way "unfixable things" a bit of a rest before you tackle them systematically.

It is possible, that #68 is not related to the code here at all. So please get this finally done.

> Could it be something while creating the .deb file ?

Could be, seems like systematic investigation is needed, please check #68.

2023-08-21 05:16 UTC, markus2330 commented on src/clima_sensor_us.rs
> +		} else if temp > 23.0
Constants not used here, and should be >= 22.

2023-08-21 05:16 UTC, markus2330 commented on src/main.rs
> +		ClimaSensorUS::new(&mut config).expect("Failed to init libmodbus connection");
Does not send error message to NC (only `Failed to init libmodbus connection`)

2023-08-21 05:16 UTC, markus2330 commented on src/main.rs
> +			if enable_weather_station {
This can be easily avoided by letting handle do nothing if the weather station is not enabled.

2023-08-21 05:16 UTC, markus2330 commented on doc/libmodbus-troubles.md
> +To solve this issue we had to use the right function (`0x01`, `0x02`, ...) for the chosen register. The function for any register is in the documentation of the [weatherstation](https://www.vetterag.
```suggestion
To solve this issue we had to use the right function (`0x01`, `0x02`, ...) for the chosen register.
The function for any register is in the documentation of the [weatherstation](https://www.vetterag.ch/images/pdf/thies/BA/4.920x.x0.xxx_ClimaSensor_US_d.pdf) or [inverter](https://loxwiki.atlassian.net/wiki/spaces/LOX/pages/1605274474/Goodwe+GW10+ET+MODBUS+TCP+IP?preview=/1605274474/1605274552/Goodwe_Modbus_Protocol_Hybrid_ET_EH_BH_BT__ARM205%20HV__V1.7%20_%20Read%20Only_20200226%20(1).pdf).
```

2023-08-21 07:30 UTC, fel115 commented on src/main.rs
> +			if enable_weather_station {
I did it implicitly, by checking the value of the Modbus connection. If it is set to `None` no state change is returned. But should it be explicitly been checked in the `handle()` function?

2023-08-21 10:45 UTC, markus2330 commented on src/main.rs
> +			if enable_weather_station {
Yes, all the other modules handle this internally in handle, I don't see a reason why this module should be different in this regard. Do you already have any plans how the new module system should be? (E.g. with async handle entry point?)

2023-08-21 11:07 UTC, fel115 commented on src/main.rs
> +			if enable_weather_station {
Ok. 
According async I need to talk with @horenso, but the sync modules only need to be enabled or disabled in elektra config.

2023-08-22 09:55 UTC, markus2330 commented
CI system is failing now. Let get us done before you start refactoring :rocket:

2023-08-22 14:46 UTC, fel115 commented
I think the error says, that the `asm/param.h` header couldn't be found.
```bash
[2023-08-21T08:16:15.708Z]   /usr/include/linux/param.h:5:10: fatal error: 'asm/param.h' file not found

[2023-08-21T08:16:15.708Z]   /usr/include/linux/param.h:5:10: fatal error: 'asm/param.h' file not found, err: true

[2023-08-21T08:16:15.708Z]   thread 'main' panicked at 'could not reate binding: ()', /usr/local/cargo/git/checkouts/libmodbus-rs-6e4ee3ccb3d4329a/ad36c57/libmodbus-sys/build.rs:126:10

[2023-08-21T08:16:15.708Z]   note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

[2023-08-21T08:16:15.708Z] warning: build failed, waiting for other jobs to finish...

[2023-08-21T08:16:23.568Z] cargo-deb: build failed
```

But I found the following files on in the docker image:
```bash
/usr/include/x86_64-linux-gnu/asm/param.h
/usr/include/asm-generic/param.h
/usr/arm-linux-gnueabihf/include/asm-generic/param.h
/usr/arm-linux-gnueabihf/include/asm/param.h
```

Maybe we are using the wrong `param.h` or we need to tell cargo to use one of them. On the olimex board I found this header-file:
```bash
/usr/include/arm-linux-gnueabihf/asm/param.h
```

# 1 Attempt using `ln`
```bash
ln -s /usr/arm-linux-gnueabihf/include/asm /usr/include/arm-linux-gnueabihf/asm
```
compiling libmodbus-sys seems to work now, but I get another error.
## Following error
```bash
 Compiling libmodbus-sys v1.0.0 (https://github.com/ElektraInitiative/libmodbus-rs.git#ad36c57f)
   Compiling libmodbus v1.0.0 (https://github.com/ElektraInitiative/libmodbus-rs.git#ad36c57f)
   Compiling opensesame v0.7.9 (/home/smod/Bachelorarbeit/GitHub/opensesame)
error: linking with `arm-linux-gnueabihf-gcc` failed: exit status: 1
  |
  = note: "arm-linux-gnueabihf-gcc" "/tmp/rustcXsXwkr/symbols.o" "/home/smod/Bachelorarbeit/GitHub/opensesame/target/armv7-unknown-linux-gnueabihf/release/deps/opensesame-64244b3ff678d10c.opensesame.1f5581e4-cgu.0.rcgu.o" "/home/smod/Bachelorarbeit/GitHub/opensesame/target/armv7-unknown-linux-gnueabihf/release/deps/opensesame-64244b3ff678d10c.opensesame.1f5581e4-cgu.1.rcgu.o" "/home/smod/Bachelorarbeit/GitHub/opensesame/target/armv7-unknown-linux-gnueabihf/release/deps/opensesame-64244b3ff678d10c.opensesame.1f5581e4-cgu.10.rcgu.o" "/home/smod/Bachelorarbeit/GitHub/opensesame/target/armv7-unknown-linux-gnueabihf/release/deps/opensesame-64244b3ff678d10c.opensesame.1f5581e4-cgu.11.rcgu.o" "/home/smod/Bachelorarbeit/GitHub/opensesame/target/armv7-unknown-linux-gnueabihf/release/deps/opensesame-64244b3ff678d10c.opensesame.1f5581e4-cgu.12.rcgu.o" "/home/smod/Bachelorarbeit/GitHub/opensesame/target/armv7-unknown-linux-gnueabihf/release/deps/opensesame-64244b3ff678d10c.opensesame.1f5581e4-cgu.13.rcgu.o" "/home/smod/Bachelorarbeit/GitHub/opensesame/target/armv7-unknown-linux-gnueabihf/release/deps/opensesame-64244b3ff678d10c.opensesame.1f5581e4-cgu.14.rcgu.o" "/home/smod/Bachelorarbeit/GitHub/opensesame/target/armv7-unknown-linux-gnueabihf/release/deps/opensesame-64244b3ff678d10c.opensesame.1f5581e4-cgu.15.rcgu.o" "/home/smod/Bachelorarbeit/GitHub/opensesame/target/armv7-unknown-linux-gnueabihf/release/deps/opensesame-64244b3ff678d10c.opensesame.1f5581e4-cgu.2.rcgu.o" "/home/smod/Bachelorarbeit/GitHub/opensesame/target/armv7-unknown-linux-gnueabihf/release/deps/opensesame-64244b3ff678d10c.opensesame.1f5581e4-cgu.3.rcgu.o" "/home/smod/Bachelorarbeit/GitHub/opensesame/target/armv7-unknown-linux-gnueabihf/release/deps/opensesame-64244b3ff678d10c.opensesame.1f5581e4-cgu.4.rcgu.o" "/home/smod/Bachelorarbeit/GitHub/opensesame/target/armv7-unknown-linux-gnueabihf/release/deps/opensesame-64244b3ff678d10c.opensesame.1f5581e4-cgu.5.rcgu.o" "/home/smod/Bachelorarbeit/GitHub/opensesame/target/armv7-unknown-linux-gnueabihf/release/deps/opensesame-64244b3ff678d10c.opensesame.1f5581e4-cgu.6.rcgu.o" "/home/smod/Bachelorarbeit/GitHub/opensesame/target/armv7-unknown-linux-gnueabihf/release/deps/opensesame-64244b3ff678d10c.opensesame.1f5581e4-cgu.7.rcgu.o" "/home/smod/Bachelorarbeit/GitHub/opensesame/target/armv7-unknown-linux-gnueabihf/release/deps/opensesame-64244b3ff678d10c.opensesame.1f5581e4-cgu.8.rcgu.o" "/home/smod/Bachelorarbeit/GitHub/opensesame/target/armv7-unknown-linux-gnueabihf/release/deps/opensesame-64244b3ff678d10c.opensesame.1f5581e4-cgu.9.rcgu.o" "/home/smod/Bachelorarbeit/GitHub/opensesame/target/armv7-unknown-linux-gnueabihf/release/deps/opensesame-64244b3ff678d10c.5g4y87cs9c17k125.rcgu.o" "-Wl,--as-needed" "-L" "/home/smod/Bachelorarbeit/GitHub/opensesame/target/armv7-unknown-linux-gnueabihf/release/deps" "-L" "/home/smod/Bachelorarbeit/GitHub/opensesame/target/release/deps" "-L" "/usr/lib" "-L" "/usr/lib/x86_64-linux-gnu" "-L" "/usr/lib/arm-linux-gnueabihf" "-L" "/home/smod/Bachelorarbeit/GitHub/opensesame/target/armv7-unknown-linux-gnueabihf/release/build/libssh2-sys-132c8fccb0a99275/out/build" "-L" "/home/smod/Bachelorarbeit/GitHub/opensesame/target/armv7-unknown-linux-gnueabihf/release/build/libz-sys-29c1330973dae8d9/out/lib" "-L" "/home/smod/Bachelorarbeit/GitHub/opensesame/target/armv7-unknown-linux-gnueabihf/release/build/libz-sys-29c1330973dae8d9/out/lib" "-L" "/usr/local/rustup/toolchains/1.67.0-x86_64-unknown-linux-gnu/lib/rustlib/armv7-unknown-linux-gnueabihf/lib" "-Wl,-Bstatic" "/home/smod/Bachelorarbeit/GitHub/opensesame/target/armv7-unknown-linux-gnueabihf/release/deps/libsignal_hook-232c3e321de410c5.rlib" "/home/smod/Bachelorarbeit/GitHub/opensesame/target/armv7-unknown-linux-gnueabihf/release/deps/libsystemstat-b4e2528bd1581b04.rlib" "/home/smod/Bachelorarbeit/GitHub/opensesame/target/armv7-unknown-linux-gnueabihf/release/deps/libnom-eed8580659cec4ba.rlib" "/home/smod/Bachelorarbeit/GitHub/opensesame/target/armv7-unknown-linux-gnueabihf/release/deps/libbytesize-44298f8891546820.rlib" "/home/smod/Bachelorarbeit/GitHub/opensesame/target/armv7-unknown-linux-gnueabihf/release/deps/libsunrise-045d42ac772bc3eb.rlib" "/home/smod/Bachelorarbeit/GitHub/opensesame/target/armv7-unknown-linux-gnueabihf/release/deps/libchrono-5bdd4b7f5b53a1f8.rlib" "/home/smod/Bachelorarbeit/GitHub/opensesame/target/armv7-unknown-linux-gnueabihf/release/deps/libnum_integer-d9af4c21563f09e1.rlib" "/home/smod/Bachelorarbeit/GitHub/opensesame/target/armv7-unknown-linux-gnueabihf/release/deps/libnum_traits-54972ef245fb6823.rlib" "/home/smod/Bachelorarbeit/GitHub/opensesame/target/armv7-unknown-linux-gnueabihf/release/deps/libgettextrs-75fa23ebca410aa1.rlib" "/home/smod/Bachelorarbeit/GitHub/opensesame/target/armv7-unknown-linux-gnueabihf/release/deps/libgettext_sys-01062f5b401ca7ec.rlib" "/home/smod/Bachelorarbeit/GitHub/opensesame/target/armv7-unknown-linux-gnueabihf/release/deps/liblocale_config-cd92e52d176646ed.rlib" "/home/smod/Bachelorarbeit/GitHub/opensesame/target/armv7-unknown-linux-gnueabihf/release/deps/libregex-fa65e9025a48d00a.rlib" "/home/smod/Bachelorarbeit/GitHub/opensesame/target/armv7-unknown-linux-gnueabihf/release/deps/libaho_corasick-644f3fd55dda16e2.rlib" "/home/smod/Bachelorarbeit/GitHub/opensesame/target/armv7-unknown-linux-gnueabihf/release/deps/libregex_syntax-952e1a9af526ba55.rlib" "/home/smod/Bachelorarbeit/GitHub/opensesame/target/armv7-unknown-linux-gnueabihf/release/deps/libssh2-ec5de5b962ce88d3.rlib" "/home/smod/Bachelorarbeit/GitHub/opensesame/target/armv7-unknown-linux-gnueabihf/release/deps/liblibssh2_sys-ffbc572a3196bff5.rlib" "/home/smod/Bachelorarbeit/GitHub/opensesame/target/armv7-unknown-linux-gnueabihf/release/deps/liblibz_sys-5321df6e86a3890b.rlib" "/home/smod/Bachelorarbeit/GitHub/opensesame/target/armv7-unknown-linux-gnueabihf/release/deps/libbme280-706788cffa5e3da7.rlib" "/home/smod/Bachelorarbeit/GitHub/opensesame/target/armv7-unknown-linux-gnueabihf/release/deps/liblinux_embedded_hal-3e6f9c7cf960282b.rlib" "/home/smod/Bachelorarbeit/GitHub/opensesame/target/armv7-unknown-linux-gnueabihf/release/deps/libsysfs_gpio-1fae2f38f1dfee15.rlib" "/home/smod/Bachelorarbeit/GitHub/opensesame/target/armv7-unknown-linux-gnueabihf/release/deps/libspidev-0 [...]

2023-08-22 17:29 UTC, 4ydan commented on scripts/jenkins/Dockerfile_cross
> +    binutils-arm-linux-gnueabihf \
This is redundant I think.

2023-08-22 17:43 UTC, markus2330 commented
It seems to build now. Does the produced `.deb` already work? Please say when I should review.

> I think the error says

Thx, very nice analysis.

> skipping incompatible /usr/lib/x86_64-linux-gnu/libc.so

Looks like arm libc is missing?

2023-08-22 19:38 UTC, fel115 commented on scripts/jenkins/Dockerfile_cross
> +    binutils-arm-linux-gnueabihf \
So I can remove this line?

2023-08-22 20:37 UTC, fel115 commented
I added the `libmodbus-dev:armhf` and now it's working. @4ydan pls review the Dockerfile.

2023-08-23 12:44 UTC, 4ydan commented on scripts/jenkins/Dockerfile_cross
> +    binutils-arm-linux-gnueabihf \
Yes, its probably already installed in some other package, but can also leave it for more robustness, idk?

2023-08-23 15:07 UTC, merged