Usecases for publishing data
ElektraInitiative/opensesame pull request #53
Opened 2023-08-09 14:24 UTC by fel115

2023-08-09 17:45 UTC, markus2330 requested changes
Looks quite good, a few improvements so that it is a proper use case and fully fulfills the requirements.

2023-08-09 17:45 UTC, markus2330 commented on doc/usecases/assigned/public_publishing_of_data_for_anyone_interested.md
> +- **Scope:** Clima-Sensor-US - Module
```suggestion
- **Scope:** Clima-Sensor-US
```

2023-08-09 17:45 UTC, markus2330 commented on doc/usecases/assigned/public_publishing_of_data_for_anyone_interested.md
> +- **Level:** Backend
```suggestion
- **Level:** User Goal
```

2023-08-09 17:45 UTC, markus2330 commented on doc/usecases/assigned/public_publishing_of_data_for_anyone_interested.md
> +- **Actors** Thies-Clima-Sensor, Opensensemap
Opensesame is probably also involved.

```suggestion
- **Actors** Thies-Clima-Sensor, Opensesame, Opensensemap
```

2023-08-09 17:45 UTC, markus2330 commented on doc/usecases/assigned/public_publishing_of_data_for_anyone_interested.md
> +	- The user has configured opensesame to use sensor mode.
This is only temporary workaround and hopefully is not needed long, so instead it should be:

```suggestion
	- The user has configured opensesame to use Clima-Sensor-US  and to publish to opensensemap.
```

2023-08-09 17:45 UTC, markus2330 commented on doc/usecases/assigned/public_publishing_of_data_for_anyone_interested.md
> +	- Update frequency is set.
Not relevant for user, it is fixed with a minute.

2023-08-09 17:45 UTC, markus2330 commented on doc/usecases/assigned/public_publishing_of_data_for_anyone_interested.md
> +	- Transmit the JSON string to the Opensensemap API.
```suggestion
	- Opensesame transmits the JSON string to the Opensensemap API every minute.
```

2023-08-14 07:39 UTC, fel115 commented on doc/usecases/assigned/public_publishing_of_data_for_anyone_interested.md
> +	- Sensor IDs are set in constants.
We used constants to store the IDs of the sensors, which are directly in the source code.

2023-08-14 07:41 UTC, fel115 commented on doc/usecases/assigned/public_publishing_of_data_for_anyone_interested.md
> +	- Update frequency is set.
Ok, so the update frequency should not be set by the user?

2023-08-14 09:07 UTC, markus2330 commented on doc/usecases/assigned/public_publishing_of_data_for_anyone_interested.md
> +	- Update frequency is set.
I don't see why it is needed. The web interface seems to use hard-coded 1 minute, or can this be changed? But even if, I don't really see why I would want to change it.
In general: if there is no need, we always go with the minimal solution and keep things hard-coded.

2023-08-14 13:58 UTC, markus2330 commented on doc/usecases/assigned/public_publishing_of_data_for_anyone_interested.md
> +	- Sensor IDs are set in constants.
Then this is not a precondition for a use case.

```suggestion
```

Please undraft, so that we can get this merged.

2023-08-14 16:33 UTC, markus2330 approved these changes
LGTM, only did very minor changes.

2023-08-18 13:06 UTC, merged