Usecase warn/alarm indoor temp
ElektraInitiative/opensesame pull request #55
Opened 2023-08-14 08:50 UTC by fel115

2023-08-14 16:34 UTC, markus2330 requested changes
Minor things forgotten.

2023-08-14 16:34 UTC, markus2330 commented on doc/usecases/assigned/public_publishing_of_data_for_anyone_interested.md
> +# Use Case: Public Publishing of data for Anyone Interested
Also here, PR doesn't seem to be branched off from master.

2023-08-14 16:34 UTC, markus2330 commented on doc/usecases/draft/warn_alarm_on_indoor_temperatures.md
> +	- The user has set up threshold values for warnings and alarms.
That sensors are connected is missing.

2023-08-14 16:34 UTC, markus2330 commented on doc/usecases/draft/warn_alarm_on_indoor_temperatures.md
> +	- If the alarm threshold is exceeded, Opensesame sends an alarm to Nextcloud.
Once the temperature goes below a cancel threshold, the warning/alarm should be canceled (but we don't go back to alarm).

2023-08-15 07:01 UTC, fel115 commented on doc/usecases/assigned/public_publishing_of_data_for_anyone_interested.md
> +# Use Case: Public Publishing of data for Anyone Interested
Yes I did because I already created the directories in the `uscases` branch

2023-08-15 07:15 UTC, fel115 commented on doc/usecases/draft/warn_alarm_on_indoor_temperatures.md
> +	- If the alarm threshold is exceeded, Opensesame sends an alarm to Nextcloud.
So we only remove the alarm/warning, but if the thresholds are exceeded we again set the alarm/warning?

2023-08-15 14:48 UTC, markus2330 commented on doc/usecases/draft/warn_alarm_on_indoor_temperatures.md
> +	- If the alarm threshold is exceeded, Opensesame sends an alarm to Nextcloud.
Similar to https://en.wikipedia.org/wiki/Hysteresis we want to avoid toggle states where small changes might trigger notifications. Same as with weather station. So release of warning must be way below the setting of a warning.

2023-08-18 11:56 UTC, markus2330 reviewed
Are they ready for review?

2023-08-18 11:56 UTC, markus2330 commented on doc/usecases/draft/warn_alarm_on_indoor_temperatures.md
> +	- The cancel threshold is set to 18 °C
No need to have the precondition if you cannot change it.

2023-08-18 13:20 UTC, merged