Use case: 'on battery' and 'low battery' warning via Nextcloud Chat
ElektraInitiative/opensesame pull request #56
Opened 2023-08-14 09:27 UTC by fel115

2023-08-14 16:23 UTC, markus2330 commented on doc/usecases/assigned/public_publishing_of_data_for_anyone_interested.md
> +# Use Case: Public Publishing of data for Anyone Interested
Seems like you didn't branch off master. Is this on purpose?

2023-08-15 07:31 UTC, fel115 commented on doc/usecases/assigned/public_publishing_of_data_for_anyone_interested.md
> +# Use Case: Public Publishing of data for Anyone Interested
Yes, like in PR #55. But I think there shouldn't be merging problems. Maybe it would have been better if I only created a PR that creates the directories.

2023-08-15 17:18 UTC, markus2330 requested changes
Further review for usecases.

2023-08-16 09:04 UTC, fel115 commented on doc/usecases/draft/on_battery_low_battery_warning_via_nextcloud.md
> +	- If the battery is not in use and the 'low battery' threshold is not exceeded, no action is taken.
I meant the board gets its energy from the power adapter, so the board doesn't use the energy of the battery. Like a USV, if there is a power failure the board is able to run and send notification (if the network is up).

2023-08-18 13:05 UTC, merged