Implementation MOD-IR-TEMP
ElektraInitiative/opensesame pull request #63
Opened 2023-08-18 10:50 UTC by fel115

Issue: #62 

@markus2330 please review, the functionality. What should be implemented in handle()?  When should something be triggered? There are two temperature values the ambient and the temperature of an object, how should they be used?

2023-08-21 10:50 UTC, markus2330 commented
> What should be implemented in handle()?

In the current module system it always should update the values (to be stored in the struct)

> When should something be triggered?

When the value changes according the use cases.

> There are two temperature values the ambient and the temperature of an object, how should they be used?

If one of them goes below the threshold it should trigger and only if both go below the warning should be cancelled.

2023-08-21 16:41 UTC, fel115 commented
Need to be tested, waiting for Nextcloud to be reachable.
# TODO if code works
- [ ] implement Translation

2023-08-22 05:46 UTC, markus2330 commented
Nextcloud (and everything else) is up again.

2023-08-22 09:53 UTC, markus2330 requested changes
Thx for the the module, mostly good work, nice user-facing strings. Probably it is best if you first decide about the interface of how modules should look like (constructor, handle) so that we soon get consistency.

General documentation about the mod-ir module (.md file) and spec file is missing.

2023-08-22 09:53 UTC, markus2330 commented on lang/de_AT.po
> +msgstr "⚠️ Initialisierung von MOD-IR-TEMP ist fehlgeschlagen: InvalidInputData"
Shouldn't be needed? (Generic one enough)

2023-08-22 09:53 UTC, markus2330 commented on src/main.rs
> +		let mut ir_temp = ModIrTemps::new_default();
Good placement but the constructor's name is different. Please also be consistent in singular name of modules. I think ModIR is enough. Pass config to constructor as for other modules.

```suggestion
		let mut ir_temp = ModIR::new(&mut config);
```

2023-08-22 09:53 UTC, markus2330 commented on src/main.rs
> +					nc.ping(gettext("⚠️ Failed to init MOD-IR-TEMP: ChecksumMismatch"));
Maybe this already fixes the problem of multiple translation strings?

```suggestion
					nc.ping(gettext("⚠️ Failed to init MOD-IR: {}", "ChecksumMismatch"));
```

2023-08-22 09:53 UTC, markus2330 commented on src/mod_ir_temp.rs
> +pub struct ModIrTemps {
Please add some documentation to the individual elements.

```suggestion
pub struct ModIR {
```

2023-08-22 09:53 UTC, markus2330 commented on src/mod_ir_temp.rs
> +	_emissivity: f32,
Why underscore?

2023-08-22 09:53 UTC, markus2330 commented on src/mod_ir_temp.rs
> +	//Generate default instanz of struct.
```suggestion
	//Generate default instance of struct.
```

2023-08-22 09:53 UTC, markus2330 commented on src/mod_ir_temp.rs
> +	//The parameter emissivity can be choosen between 0.0 and 1.0
How did you choose it and why?

2023-08-22 09:53 UTC, markus2330 commented on src/main.rs
> +			config.get::<String>("ir_temp/device"),
spec missing. And I would call it mod/ir or simply ir.

2023-08-22 10:07 UTC, fel115 commented on src/mod_ir_temp.rs
> +	//The parameter emissivity can be choosen between 0.0 and 1.0
I used the default value, which is set to `1`. However, the emissivity only needs to be adjusted if we are using a specific object for measurement, as indicated [here](https://en.wikipedia.org/wiki/Emissivity). Therefore, I incorporated this function to allow for setting the emissivity when required in certain use cases.

2023-08-22 10:08 UTC, fel115 commented on src/mod_ir_temp.rs
> +	_emissivity: f32,
To remove the warning of emissivity isn't used.

2023-08-22 10:27 UTC, fel115 commented on lang/de_AT.po
> +msgstr "⚠️ Initialisierung von MOD-IR-TEMP ist fehlgeschlagen: InvalidInputData"
The translation is not needed for these two?

2023-08-22 10:32 UTC, fel115 commented on lang/de_AT.po
> +msgstr "⚠️ Initialisierung von MOD-IR-TEMP ist fehlgeschlagen: InvalidInputData"
Ok, I think I know what you mean.

2023-08-22 17:32 UTC, markus2330 commented on src/mod_ir_temp.rs
> +	//The parameter emissivity can be choosen between 0.0 and 1.0
Great, please add this info to this comment. It is okay for now if it stays hard-coded to 1.0 for now.

2023-08-24 09:49 UTC, markus2330 approved these changes
Let us get this merged before the refactoring. Please rebase/fix conflicts.

2023-08-24 09:49 UTC, markus2330 commented on src/mod_ir_temp.rs
> +	/// It returns 'ChangedToBothToHot' if both thresholds have been exceeded.
Some o missing (also in other lines):

```suggestion
	/// It returns 'ChangedToBothTooHot' if both thresholds have been exceeded.
```

2023-08-28 13:11 UTC, markus2330 approved these changes
Small problem in the spec but this can be also fixed while refactoring.

2023-08-28 13:11 UTC, markus2330 commented on files/opensesame.spec
> +description=How often to get new data, depends on how often handle() is called
This should be defined by the implementation and documented here.

2023-08-28 13:11 UTC, markus2330 commented on files/opensesame.spec
> +default=60
If this is simply a number in seconds or similar it would be easier for the user.

2023-08-28 13:11 UTC, merged

2023-08-28 13:11 UTC, markus2330 commented
Great work, looking forward to progress in refactoring soon! :rocket:

2023-08-28 14:33 UTC, fel115 commented on files/opensesame.spec
> +default=60
For now, it depends on how often the handle function is called. This will be different in the async approach.